name: Build

on:
  create:
    tag:
      - "v*"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --immutable

      - name: Test
        run: yarn test:all

      - name: Build
        run: |
          yarn clean:all
          yarn build:all

      - name: Lint
        run: yarn lint:all

      - name: Set publish version from tag
        id: version
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo ::set-output name=VERSION::$(echo '${{ github.ref }}' | cut -c 12-)

      - name: Publish
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          node ./packages/ts-project-scripts/lib/index.js \
            publish \
            --access public \
            --set-version ${{ steps.version.outputs.VERSION }} \
            @jtbennett/ts-project-cli-utils \
            @jtbennett/ts-project-scripts \
            @jtbennett/create-ts-project
